
#
#	MySql Server
#
FROM ubuntu:14.04

# Root Passwort wird gesetzt 
RUN echo 'mysql-server mysql-server/root_password password LucaHarisCedric' | debconf-set-selections 
RUN echo 'mysql-server mysql-server/root_password_again password LucaHarisCedric' | debconf-set-selections 

# Installation
RUN apt-get update && apt-get install -y mysql-server

# mysql config - Port fuer alle Hosts oeffnen
RUN sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf

#Öffnet Port 3306
EXPOSE 3306

#Erstellt Datenbank "Wordpress" und vergibt dem User "Wordpress" rechte auf die Datenbank "Wordpress"
RUN echo "CREATE DATABASE wordpress" | mysql -uroot -pLucaHaris2020
RUN echo "GRANT ALL ON wordpress.* TO 'wordpressuser'@'localhost'" | mysql -uroot -pLucaHaris2020
RUN echo "flush privileges" | mysql -uroot -pLucaHaris2020
RUN sudo service mysql start


VOLUME /var/lib/mysql

